title: ""
description: "AI chat assistant for Google Slides that helps you brainstorm ideas and craft better slide content, privately and effortlessly, within your workflow."
theme: jekyll-theme-cayman
show_downloads: false
