title: "<img src='https://orcaechoai.github.io/OrcaEdit-Chatbot/assets/Logo%20dark%20blue.png' alt='Orcarina logo' width='120' style='border-radius:12px;'><br>Orcarina"
description: "AI chat assistant for Google Slides that helps you brainstorm ideas and craft better slide content, privately and effortlessly, within your workflow."
theme: jekyll-theme-cayman
show_downloads: false
